local detail = false
---@module 'oil'
---@type oil.SetupOpts
return {
  -- "stevearc/oil.nvim",
  -- lazy = false,
  -- keys = {
  --   {
  --     "<leader>e",
  --     function()
  --       if vim.w.is_oil_win then
  --         require("oil").close()
  --       else
  --         require("oil").open_float(nil, { preview = {} })
  --       end
  --     end,
  --     desc = "Open file explorer",
  --   },
  -- },
  -- opts = {
  --   skip_confirm_for_simple_edits = true,
  --   columns = {
  --     "icon",
  --   },
  --   delete_to_trash = true,
  --   git = {
  --     -- Return true to automatically git add/mv/rm files
  --     add = function(path)
  --       return true
  --     end,
  --     mv = function(src_path, dest_path)
  --       return true
  --     end,
  --     rm = function(path)
  --       return true
  --     end,
  --   },
  --   win_options = {
  --     signcolumn = "yes:2",
  --   },
  --   float = {
  --     -- Padding around the floating window
  --     padding = 2,
  --     max_width = 140,
  --     max_height = 30,
  --     border = "rounded",
  --     win_options = {
  --       winblend = 0,
  --     },
  --     -- preview_split: Split direction: "auto", "left", "right", "above", "below".
  --     preview_split = "right",
  --     -- This is the config that will be passed to nvim_open_win.
  --     -- Change values here to customize the layout
  --     override = function(conf)
  --       return conf
  --     end,
  --   },
  --   preview_win = {
  --     -- Whether the preview window is automatically updated when the cursor is moved
  --     update_on_cursor_moved = true,
  --     -- How to open the preview window "load"|"scratch"|"fast_scratch"
  --     preview_method = "fast_scratch",
  --     -- A function that returns true to disable preview on a file e.g. to avoid lag
  --     disable_preview = function(filename)
  --       return false
  --     end,
  --     -- Window-local options to use for preview window buffers
  --     win_options = {},
  --   },
  --   keymaps = {
  --     ["<C-s>"] = {
  --       desc = "Save changes",
  --       callback = function()
  --         require("oil").save()
  --       end,
  --     },
  --     ["q"] = {
  --       desc = "Save changes and close",
  --       callback = function()
  --         require("oil").save({}, function()
  --           vim.cmd.quit()
  --         end)
  --       end,
  --     },
  --     ["gd"] = {
  --       desc = "Toggle file detail view",
  --       callback = function()
  --         detail = not detail
  --         if detail then
  --           require("oil").set_columns({ "icon", "permissions", "size" })
  --         else
  --           require("oil").set_columns({ "icon" })
  --         end
  --       end,
  --     },
  --     -- [";"] = { "actions.parent", mode = "n" },
  --     ["h"] = { "actions.parent", mode = "n" },
  --     ["l"] = { "actions.select", mode = "n" },
  --     ["<C-h>"] = { "actions.select", opts = { horizontal = true }, desc = "Open the entry in a horizontal split" },
  --     ["<C-v>"] = { "actions.select", opts = { vertical = true }, desc = "Open the entry in a vertical split" },
  --   },
  --   view_options = {
  --     is_hidden_file = function(name, bufnr)
  --       return name ~= ".." and not string.match(name, ".env") and vim.startswith(name, ".")
  --     end,
  --   },
  -- },
  -- config = function(_, opts)
  --   require("oil").setup(opts)
  --
  --   local augroup = vim.api.nvim_create_augroup("OilOpenPreview", { clear = true })
  --   local is_previewing = false
  --   -- Autocommand for trigering preview when entering neovim with `nvim .`
  --   vim.api.nvim_create_autocmd("User", {
  --     pattern = "OilEnter",
  --     group = augroup,
  --     callback = function()
  --       if is_previewing then
  --         return
  --       end
  --       is_previewing = true
  --       require("oil").open_preview()
  --     end,
  --   })
  -- end,
  -- dependencies = { { "nvim-mini/mini.icons", opts = {} } },
}
